name = "TinyDronesSim"
uuid = "72c9fe2e-f218-4e33-9937-2895c797bef7"
authors = ["Yunus Zenichowski <y.zenichowski@gmail.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"

[compat]
StaticArrays = "1.9.9"
StaticStrings = "0.2.6"
